### ISSUE TITLE
tool for drawing sprites

### ISSUE THREAD

**Issue by lccsgf** [JericLew/ME3241_Project#1]
I am wondering what tool you used for drawing sprites. Thank you in advance!!!

**Comment by JericLew** [comment]
Hi, I used a rather round about way 

1. GIMP (open source drawing tool)
2. Draw the sprites by filling in colours on the pixels
3. export as bmp (had to select some special option which i had forgot)
4. Use the bmp2gbtile command line tool to convert it to code

I suggest using other online or offline tools as my method is very convoluted and has many things that I have kinda forgot along the way. 

Are you doing this class right now?

edit: try this https://www.piskelapp.com/p/create/sprite
can be used to export to C

**Comment by lccsgf** [comment]
Yeah, thank you. This web is really helpful!!!

**Comment by JericLew** [comment]
no problem, goodluck on the project! feel free to reach out via linkedin etc if you have any other questions
